name: 'CodeSign Windows binaries'
description: 'GitHub Action to sign Windows binaries PE(EXE/SYS/DLL/etc), CAB and MSI files using osslsigncode'
author: 'ibiqlik'

inputs:
  cmd:
    description: 'Command for osslsigncode, see https://sourceforge.net/projects/osslsigncode/files/osslsigncode/'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}

branding:
  color: green
  icon: lock
